<?php

namespace Pages\CoreBundle\Repository;

/**
 * CommunRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunRepository extends \Doctrine\ORM\EntityRepository
{
}
